com.android.cts.priv.ctsshim
com.qualcomm.qti.qms.service.telemetry
 com.google.android.youtube
 com.android.internal.display.cutout.emulation.corner
 com.google.android.ext.services
 com.android.internal.display.cutout.emulation.double
 com.android.providers.telephony
 com.android.dynsystem
 com.goodix.fingerprint
 com.google.android.googlequicksearchbox
 com.android.providers.calendar
 org.telegram.messenger
 com.android.providers.media
 com.qti.service.colorservice
 com.android.theme.icon.square
 com.google.android.onetimeinitializer
 com.google.android.ext.shared
 com.android.internal.systemui.navbar.gestural_wide_back
 com.android.wallpapercropper
 com.android.theme.color.cinnamon
 com.android.protips
 com.android.theme.icon_pack.rounded.systemui
 com.android.documentsui
 com.android.externalstorage
 com.qualcomm.uimremoteclient
 com.android.htmlviewer
 com.whatsapp
 com.qualcomm.qti.uceShimService
 com.android.companiondevicemanager
 com.android.mms.service
 com.qualcomm.qti.qms.service.connectionsecurity
 com.android.providers.downloads
 com.longcheertel.midtest
 com.google.android.apps.messaging
 com.android.networkstack.inprocess
 com.android.theme.icon_pack.rounded.android
 vendor.qti.hardware.cacert.server
 com.qualcomm.qti.callenhancement
 com.qualcomm.qti.telephonyservice
 com.mixplorer.addon.archive
 com.android.theme.icon_pack.circular.themepicker
 com.google.android.overlay.gmsgsaconfig
 vendor.qti.iwlan
 com.google.android.configupdater
 com.qualcomm.qti.optinoverlay
 com.google.android.overlay.modules.permissioncontroller
 com.qualcomm.uimremoteserver
 com.qti.confuridialer
 com.longcheertel.modemlog
 com.google.ar.lens
 com.android.providers.downloads.ui
 com.android.vending
 com.android.pacprocessor
 com.android.simappdialog
 com.android.internal.display.cutout.emulation.tall
 com.android.certinstaller
 com.android.theme.color.black
 com.android.carrierconfig
 com.google.android.marvin.talkback
 com.android.theme.color.green
 com.android.theme.color.ocean
 com.android.theme.color.space
 com.wapi.wapicertmanage
 com.android.internal.systemui.navbar.threebutton
 com.google.android.apps.work.oobconfig
 com.qti.qualcomm.datastatusnotification
 android
 com.qualcomm.qti.callfeaturessetting
 com.qualcomm.wfd.service
 com.android.theme.icon_pack.rounded.launcher
 com.qti.qualcomm.deviceinfo
 android.autoinstalls.config.Xiaomi.jasmine
 com.android.egg
 com.android.mtp
 com.android.ons
 com.android.stk
 com.android.launcher3
 com.android.backupconfirm
 com.goodix.gftest
 com.google.android.deskclock
 com.android.internal.systemui.navbar.twobutton
 org.codeaurora.ims
 com.android.statementservice
 com.android.hotspot2
 com.google.android.gm
 android.overlay.target
 com.google.android.apps.tachyon
 com.android.settings.intelligence
 com.android.internal.systemui.navbar.gestural_extra_wide_back
 com.google.android.permissioncontroller
 com.google.android.setupwizard
 com.qualcomm.qcrilmsgtunnel
 com.android.providers.settings
 com.android.sharedstoragebackup
 com.google.android.music
 com.android.printspooler
 com.android.theme.icon_pack.filled.settings
 com.android.dreams.basic
 com.google.android.overlay.modules.ext.services
 com.miui.bugreport
 com.android.se
 com.android.inputdevices
 com.qualcomm.qti.biometrics.fingerprint.service
 com.google.android.apps.wellbeing
 com.google.android.dialer
 com.android.bips
 com.qti.dpmserviceapp
 com.google.android.apps.nbu.files
 com.android.theme.icon_pack.circular.settings
 com.fingerprints.extension.service
 com.qti.xdivert
 com.android.musicfx
 com.google.android.overlay.gmsconfig
 com.google.android.apps.docs
 com.google.android.apps.maps
 com.google.android.modulemetadata
 com.collabora.libreoffice
 com.android.cellbroadcastreceiver
 com.google.android.webview
 com.android.theme.icon.teardrop
 com.qualcomm.qti.simsettings
 com.google.android.contacts
 com.android.server.telecom
 com.google.android.syncadapters.contacts
 com.android.keychain
 com.android.camera
 com.google.android.calculator
 com.android.chrome
 com.android.theme.icon_pack.filled.systemui
 com.google.android.packageinstaller
 com.google.android.gms
 com.google.android.gsf
 com.google.android.ims
 com.google.android.tag
 com.google.android.tts
 com.google.android.gmsintegration
 com.qualcomm.qti.qtisystemservice
 com.android.calllogbackup
 com.google.android.partnersetup
 com.android.localtransport
 com.google.android.videos
 com.android.carrierdefaultapp
 com.dsi.ant.server
 com.qualcomm.qti.remoteSimlockAuth
 com.android.theme.font.notoserifsource
 com.android.theme.icon_pack.filled.android
 com.android.proxyhandler
 com.qualcomm.qti.workloadclassifier
 com.android.theme.icon_pack.circular.systemui
 com.miui.spock
 com.google.android.overlay.modules.permissioncontroller.forframework
 com.google.android.feedback
 com.google.android.printservice.recommendation
 com.google.android.apps.photos
 com.google.android.calendar
 com.android.managedprovisioning
 com.fingerprints.sensortesttool
 com.android.dreams.phototable
 com.mixplorer
 com.mixplorer.addon.pdf
 com.android.providers.partnerbookmarks
 com.android.smspush
 com.android.wallpaper.livepicker
 com.android.theme.icon.squircle
 com.longcheertel.AutoTest
 com.android.storagemanager
 com.android.bookmarkprovider
 com.android.settings
 com.qualcomm.qti.cne
 com.qualcomm.qti.ims
 com.qualcomm.qti.smq
 com.google.android.apps.nbu.paisa.user
 com.android.theme.icon_pack.filled.launcher
 com.android.networkstack.permissionconfig
 com.google.android.projection.gearhead
 com.qualcomm.location
 com.google.android.apps.turbo
 com.android.cts.ctsshim
 com.android.theme.icon_pack.circular.launcher
 com.qualcomm.qti.services.secureui
 com.android.vpndialogs
 com.longcheertel.cit
 com.google.android.keep
 com.android.phone
 com.android.shell
 com.android.theme.icon_pack.filled.themepicker
 com.android.wallpaperbackup
 com.android.providers.blockednumber
 com.android.providers.userdictionary
 com.android.emergency
 com.qualcomm.qti.seccamservice
 com.qualcomm.qti.qmmi
 com.google.android.gms.location.history
 com.android.internal.systemui.navbar.gestural
 com.android.location.fused
 com.android.theme.color.orchid
 com.android.systemui
 com.google.android.apps.youtube.music
 com.android.theme.color.purple
 com.android.bluetoothmidiservice
 com.qualcomm.qti.confdialer
 com.qualcomm.qti.poweroffalarm
 com.qualcomm.qti.networksetting
 com.android.traceur
 com.android.apppredictionservice
 com.qualcomm.qti.qms.service.trustzoneaccess
 com.google.android.apps.magazines
 com.android.bluetooth
 com.qualcomm.timeservice
 com.qualcomm.atfwd
 com.android.wallpaperpicker
 com.android.providers.contacts
 com.android.captiveportallogin
 com.android.theme.icon.roundedrect
 com.google.android.overlay.modules.modulemetadata
 com.android.internal.systemui.navbar.gestural_narrow_back
 com.android.theme.icon_pack.rounded.settings
 com.android.overlay.telephony
 com.google.android.inputmethod.latin
 com.android.theme.icon_pack.circular.android
 com.google.android.apps.restore
 com.google.android.overlay.searchlauncherconfig

